#!/usr/bin/env node
/**
 * Checks that apps/web/dist is deployable and that the tree keeps the rules the site depends on, so a mistake
 * shows up in the build log instead of in production. Ported from krupiq's preflight, which caught a deploy
 * without a build and an inline script whose CSP hash had drifted.
 *
 *   node scripts/preflight.mjs [distDir]
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(process.argv[2] ?? join(root, 'apps', 'web', 'dist'));
const src = join(root, 'apps', 'web', 'src');

const sections = [];
const section = (name) => {
  const entry = { name, problems: [], notes: [] };
  sections.push(entry);
  return entry;
};
/** Repository-relative for display; a dist outside the repository (tests) keeps its absolute path. */
const rel = (path) => (path.startsWith(root) ? relative(root, path) : path).replaceAll('\\', '/');

function* walk(dir, filter) {
  if (!existsSync(dir)) return;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(path, filter);
    else if (filter(path)) yield path;
  }
}

// 1. The build produced what the Worker's assets binding needs.
{
  const out = section('build output');
  if (!existsSync(dist)) {
    out.problems.push(`${rel(dist)} does not exist: the deploy runs after "npm run build", not instead of it.`);
  } else {
    for (const file of ['index.html', '_headers', '404.html']) {
      if (!existsSync(join(dist, file))) out.problems.push(`${rel(dist)}/${file} is missing.`);
    }
    const headers = existsSync(join(dist, '_headers')) ? readFileSync(join(dist, '_headers'), 'utf8') : '';
    if (headers && !headers.startsWith('# Generated by tools/headers.ts')) {
      out.problems.push(
        '_headers was not written by tools/headers.ts; a hand-written copy would drift from the source of truth.',
      );
    }
    for (const harness of ['dev', 'dev.html']) {
      if (existsSync(join(dist, harness))) {
        out.problems.push(
          `${rel(dist)}/${harness} exists: the development harness must not ship (scripts/postbuild.mjs removes it).`,
        );
      }
    }
    const count = [...walk(dist, () => true)].length;
    out.notes.push(`${count} files`);
  }
}

// 2. Nothing credential-shaped reaches the output or the Worker configuration.
const CREDENTIALS = [
  ['NVIDIA API key', /\bnvapi-[A-Za-z0-9_-]{16,}/],
  ['Convai or Azure key (32 hex)', /\b[0-9a-f]{32}\b/i],
  ['private key block', /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
  ['AWS access key', /\bAKIA[0-9A-Z]{16}\b/],
  ['AWS secret name', /aws_secret_access_key|aws_access_key_id/i],
  ['Stripe-style live key', /\b[sr]k_(live|test)_[0-9A-Za-z]{8,}/],
  ['Cloudflare API token assignment', /CLOUDFLARE_API_TOKEN\s*[:=]\s*["']?[A-Za-z0-9_-]{20,}/],
];
/**
 * Shapes checked in the built site only. The Postmark server token, the one Phase 1 secret, is a UUID; wrangler.jsonc
 * is exempt from that rule because it carries the D1 database_id (also a UUID) once the database is bound. Browser
 * code has no business talking to Postmark at all, so its API header and host are defects anywhere in dist.
 */
const DIST_CREDENTIALS = [
  ['Postmark server token (UUID)', /\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i],
  ['Postmark API header (the browser must never talk to Postmark)', /X-Postmark-Server-Token/i],
  ['Postmark API host (the browser must never talk to Postmark)', /\bapi\.postmarkapp\.com\b/i],
];
const TEXT = new Set(['.html', '.js', '.mjs', '.css', '.txt', '.json', '.xml', '.svg', '.webmanifest', '.map', '.md']);
{
  const out = section('credential scan');
  const scan = (text, where, patterns = CREDENTIALS) => {
    for (const [label, pattern] of patterns) {
      const hit = pattern.exec(text);
      if (hit) out.problems.push(`${where}: looks like a ${label} ("${hit[0].slice(0, 12)}...").`);
    }
  };
  let scanned = 0;
  for (const file of walk(dist, (path) => TEXT.has(extname(path)) && statSync(path).size < 2_000_000)) {
    scan(readFileSync(file, 'utf8'), rel(file), [...CREDENTIALS, ...DIST_CREDENTIALS]);
    scanned++;
  }
  const wrangler = join(root, 'wrangler.jsonc');
  if (existsSync(wrangler)) {
    const text = readFileSync(wrangler, 'utf8');
    scan(text, 'wrangler.jsonc');
    // A secret set as a plain var is the mistake the Secrets runbook exists to prevent.
    for (const match of text.matchAll(/"([A-Z][A-Z0-9_]+)"\s*:\s*"([^"]+)"/g)) {
      const [, name, value] = match;
      const secretish = /(TOKEN|SECRET|PASSWORD|API_KEY|HMAC_KEY|PRIVATE_KEY|SPEECH_KEY)$/.test(name);
      if (secretish && !name.startsWith('PUBLIC_') && !name.endsWith('SITEKEY') && value.trim()) {
        out.problems.push(
          `wrangler.jsonc sets ${name} as a var. Remove it, rotate it, and use "wrangler secret put ${name}".`,
        );
      }
    }
    scanned++;
  }
  out.notes.push(`${scanned} files`);
}

// 3. Colours live in tokens.css only, so both themes and the 3D being keep following one palette.
const HEX = /(?<![\w&-])#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})(?![\w-])/g;
const FUNCTIONAL = /\b(?:rgba?|hsla?)\(\s*\d/g;
const SVG_NEUTRALS = new Set(['#000', '#fff', '#000000', '#ffffff']);
{
  const out = section('hard-coded colours');
  const files = [
    ...walk(src, (path) => /\.(astro|css|ts)$/.test(path) && !path.endsWith(`${join('styles', 'tokens.css')}`)),
  ];
  for (const file of files) {
    const raw = readFileSync(file, 'utf8');
    if (/preflight-ignore-colours/.test(raw)) continue;
    // Comments and link targets are not colours: "#story" is an anchor, "/* #ff6a00 */" is prose. A <meta>
    // (theme-color) has to carry a literal because the browser reads it before any stylesheet exists.
    const text = raw
      .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
      .replace(/<!--[\s\S]*?-->/g, (m) => m.replace(/[^\n]/g, ' '))
      .replace(/<meta\b[^>]*>/gi, (m) => m.replace(/[^\n]/g, ' '))
      .replace(/(^|[^:])\/\/[^\n]*/g, (m, lead) => lead + ' '.repeat(m.length - lead.length))
      .replace(/\b(?:href|id|for|aria-[a-z]+|name|anchor|target|highlight)\s*[=:]\s*(["'])[^"']*\1/g, (m) =>
        ' '.repeat(m.length),
      )
      .replace(/url\(#[^)]*\)/g, (m) => ' '.repeat(m.length));
    const svgRanges = [];
    for (const m of text.matchAll(/<svg[\s\S]*?<\/svg>/gi)) svgRanges.push([m.index, m.index + m[0].length]);
    const insideSvg = (index) => svgRanges.some(([start, end]) => index >= start && index < end);
    const lineOf = (index) => text.slice(0, index).split('\n').length;
    for (const m of text.matchAll(HEX)) {
      if (insideSvg(m.index) && SVG_NEUTRALS.has(m[0].toLowerCase())) continue;
      out.problems.push(`${rel(file)}:${lineOf(m.index)}  ${m[0]} (use a token from tokens.css)`);
    }
    for (const m of text.matchAll(FUNCTIONAL)) {
      out.problems.push(`${rel(file)}:${lineOf(m.index)}  ${m[0]}...) literal (use a token, or rgba(var(--x-rgb), a))`);
    }
  }
  out.notes.push(`${files.length} files`);
}

// 4. No UI framework slipped into the bundle through a dependency.
const FRAMEWORKS = [
  ['React', /react\.(?:transitional\.)?element|__REACT_DEVTOOLS_GLOBAL_HOOK__|react-dom|_INTERNALS_DO_NOT_USE/],
  ['styled-components', /styled-components/],
  ['framer-motion', /framer-motion/],
];
{
  const out = section('framework bytes');
  let scanned = 0;
  for (const file of walk(dist, (path) => /\.(js|mjs|html)$/.test(path))) {
    const text = readFileSync(file, 'utf8');
    for (const [name, pattern] of FRAMEWORKS) {
      if (pattern.test(text)) out.problems.push(`${rel(file)} contains ${name}.`);
    }
    scanned++;
  }
  out.notes.push(`${scanned} files`);
}

// Report.
const failed = sections.filter((s) => s.problems.length);
const width = Math.max(...sections.map((s) => s.name.length));
for (const s of sections) {
  console.log(`${s.problems.length ? 'FAIL' : 'PASS'}  ${s.name.padEnd(width)}  ${s.notes.join(', ')}`);
  for (const problem of s.problems) console.log(`        - ${problem}`);
}
if (failed.length) {
  console.error(`\npreflight: ${failed.reduce((n, s) => n + s.problems.length, 0)} problem(s)`);
  process.exit(1);
}
console.log('\npreflight: dist looks deployable');
